name = "game-server"
main = "src/cloudflare-worker.ts"
compatibility_date = "2024-04-03"
workers_dev = true

# Add routes for the Pages domain
routes = [
  "civa-5ls.pages.dev/api/*",
  "civa-5ls.pages.dev/ws/*"
]

[durable_objects]
bindings = [
  { name = "GAME", class_name = "GameDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameDO"]

[observability.logs]
enabled = true

[vars]
JWT_SECRET = "development-secret-key-do-not-use-in-production"

[env.production]
vars = { JWT_SECRET = "production-secret-will-be-set-in-dashboard" }
